<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CANL-1LS0KC2" ignored="0" name="Default test" tests="10" failures="1" timestamp="11 Aug 2017 16:54:12 GMT" time="213.164" errors="0">
  <testcase name="DoTest" time="16.677" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="9.007" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="8.623" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="15.057" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="13.932" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="13.688" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="30.166" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="43.411" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="28.893" classname="com.cgi.code.testng.CallActionKeywords"/>
  <testcase name="DoTest" time="15.552" classname="com.cgi.code.testng.CallActionKeywords">
    <failure type="java.lang.AssertionError" message="expected not same">
      <![CDATA[java.lang.AssertionError: expected not same
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failSame(AssertJUnit.java:352)
	at org.testng.AssertJUnit.assertNotSame(AssertJUnit.java:310)
	at org.testng.AssertJUnit.assertNotSame(AssertJUnit.java:319)
	at com.cgi.code.testng.CallActionKeywords.DoStep(CallActionKeywords.java:350)
	at com.cgi.code.testng.CallActionKeywords.DoTest(CallActionKeywords.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- DoTest -->
</testsuite> <!-- Default test -->
